routers:
  - router_id: 172.26.1.106
    local_as: 111222
    local_address: 172.26.1.106
    bgp_port: 179
    peers:
      - peer_ip: 172.26.1.111
        peer_as: 111333
    routes:
      - prefix: "10.1.234.0/24"
        next_hop: 172.26.1.1