version: '2'

services:
    quagga:
        build:
            context: .
            dockerfile: Dockerfile.quagga
        image: 'trasa/quagga:latest'
        command: bash -c "ldpd -u root -g root"
        networks:
            trasa-net:
                ipv4_address: 172.26.1.111
        volumes:
            - ./quagga/:/etc/quagga/
    frr-near:
        image: 'cumulusnetworks/frrouting:latest'
        privileged: true
        networks:
            frr-net:
                ipv4_address: 172.26.2.112
                priority: 1000
            trasa-net:
                ipv4_address: 172.26.1.112
                priority: 900
        volumes:
            - ./frr_near/:/etc/frr/
    frr-far:
        image: 'cumulusnetworks/frrouting:latest'
        privileged: true
        networks:
            frr-net:
                ipv4_address: 172.26.2.111
        volumes:
            - ./frr_far/:/etc/frr/
    debug:
        build:
            context: .
            dockerfile: Dockerfile.trasa
        image: 'trasa/trasa:latest'
        command: bash
        networks:
            frr-net:
                ipv4_address: 172.26.2.104
            trasa-net:
                ipv4_address: 172.26.1.104
        volumes:
            - ./debug/:/tmp/debug/
    trasa:
        build:
            context: .
            dockerfile: Dockerfile.trasa
        image: 'trasa/trasa:latest'
        command: bash -c "cd trasa; python3 run.py"
        networks:
            trasa-net:
                ipv4_address: 172.26.1.106
        volumes:
            - ./:/trasa

networks:
    trasa-net:
        ipam:
            config:
                - subnet: 172.26.1.0/24
    frr-net:
        ipam:
            config:
                - subnet: 172.26.2.0/24